//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleRequest
    {
        public int RoleRequestID { get; set; }
        public int UserID { get; set; }
        public int RoleID { get; set; }
        public string Status { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Users Users { get; set; }
    }
}
