//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnfreezeRequest
    {
        public int UnfreezerequestID { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> BookId { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Users Users { get; set; }
    }
}
